#include "heating.h"

void HeatingInit(void){
  GPIOE->CRL = (GPIOE->CRL & (~(GPIO_CRL_MODE1 | GPIO_CRL_CNF1))) | (GPIO_CRL_MODE1 | GPIO_CRL_CNF1_0); // R5
  GPIOE->CRL = (GPIOE->CRL & (~(GPIO_CRL_MODE2 | GPIO_CRL_CNF2))) | (GPIO_CRL_MODE2 | GPIO_CRL_CNF2_0); // R4
  GPIOE->CRL = (GPIOE->CRL & (~(GPIO_CRL_MODE3 | GPIO_CRL_CNF3))) | (GPIO_CRL_MODE3 | GPIO_CRL_CNF3_0); // R3
  GPIOE->CRL = (GPIOE->CRL & (~(GPIO_CRL_MODE4 | GPIO_CRL_CNF4))) | (GPIO_CRL_MODE4 | GPIO_CRL_CNF4_0); // R2
  GPIOE->CRL = (GPIOE->CRL & (~(GPIO_CRL_MODE5 | GPIO_CRL_CNF5))) | (GPIO_CRL_MODE5 | GPIO_CRL_CNF5_0); // R1
  
  
  
}
